
import { Instrument_Sans } from "next/font/google";
import "../globals.css";
import Provider from "./provider";
import AuthHeader from "@/components/header/auth-header";
import { Toaster } from "react-hot-toast";
const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
});
export const metadata = {
  title: "Devlinks App",
  description: "Generated by create next app",
};

export default function AuthLayout({
                                    children,
                                  }: {
                                    children: React.ReactNode;
                                  }) {
  return (
    <html lang="en">
      <body
        className={`h-screen box-border overflow-auto ${instrumentSans.className}`}
      >
        <Provider>
          <div className="md:h-screen md:w-screen md:flex md:flex-col md:items-center md:justify-center bg-neutral-light-grey">
            <AuthHeader />
            <Toaster
              position="bottom-center"
              toastOptions={{
                duration: 5000,
                style: { background: "#333333", color: "#FAFAFA" },
              }}
            />
            <main className="bg-white md:rounded-xl">{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
